Exchange transition configuration
torquem-ch/silkrpc pull request #238
Opened 2022-03-05 16:03 UTC by enriavil1

2022-04-01 06:15 UTC, canepat requested changes

2022-04-01 06:15 UTC, canepat commented on silkrpc/commands/engine_api_test.cpp
> +
You could try getting rid of these `Dummy` classes in favor of GMock mocks

2022-04-01 07:46 UTC, enriavil1 commented on silkrpc/commands/engine_api.cpp
> +            SILKRPC_ERROR << cl_configuration.terminal_total_difficulty << " got: " << config.terminal_total_difficulty.value() << "\n";
I had to divide them because of the line length limit

2022-04-01 07:49 UTC, enriavil1 commented on silkrpc/commands/engine_api.cpp
> +    if(params.size() != 1) {
Okay will do

2022-04-01 07:49 UTC, enriavil1 commented on silkrpc/commands/engine_api.cpp
> +            SILKRPC_ERROR << cl_configuration.terminal_total_difficulty << " got: " << config.terminal_total_difficulty.value() << "\n";
I can try making the message smaller

2022-04-01 08:24 UTC, canepat commented on silkrpc/commands/engine_api.cpp
> +            SILKRPC_ERROR << cl_configuration.terminal_total_difficulty << " got: " << config.terminal_total_difficulty.value() << "\n";
Or you can simply copy my suggestion above: the message stays the same, but just one log line is generated and line length limit should not be hit

2022-04-20 15:55 UTC, canepat approved these changes

2022-04-20 15:56 UTC, merged