Adapting to silkworm changes
torquem-ch/silkrpc pull request #241
Opened 2022-03-08 21:10 UTC by Giulio2002

2022-03-12 14:01 UTC, canepat requested changes

2022-03-12 14:01 UTC, canepat commented on silkrpc/core/remote_buffer.cpp
> +bool RemoteBuffer::read_body(uint64_t block_number, const evmc::bytes32& block_hash, silkworm::BlockBody& out) const noexcept {
Probably `read_body` or `filled_body` is better than just `out` here

2022-03-12 22:01 UTC, enriavil1 commented on silkrpc/core/evm_tracing.cpp
> +#include <silkworm/third_party/evmone/lib/evmone/instructions.hpp>
I tried changing it to evmone/instructions.hpp but it fails.

2022-03-14 13:11 UTC, canepat approved these changes

2022-03-14 13:12 UTC, enriavil1 approved these changes

2022-03-14 13:12 UTC, merged