RemoteBuffer to RemoteState
torquem-ch/silkrpc pull request #244
Opened 2022-03-12 15:56 UTC by umutondersu

Changed RemoteBuffer to RemoteState on all paths

2022-03-14 13:47 UTC, canepat requested changes
Thanks a lot for contributing! Given that we're changing a couple of type names in this PR, I've just suggested the same changes also in variable names,

2022-03-14 13:47 UTC, canepat commented on silkrpc/core/evm_executor.hpp
> +    state::RemoteState buffer_;
After renaming the variable type `RemoteBuffer` as `RemoteState`, also the variable name `buffer_` should be renamed `remote_state_`

2022-03-14 13:47 UTC, canepat commented on silkrpc/core/remote_buffer.hpp
> +    AsyncRemoteState async_buffer_;
Same as above: probably `async_state_` is now better than `async_buffer_`

2022-03-14 13:47 UTC, canepat commented on silkrpc/core/remote_buffer_test.cpp
> +        AsyncRemoteState arb{io_context, db_reader, block_number};
Same as above: probably `ars` or `state` could be better now than `arb`

2022-03-14 13:47 UTC, canepat commented on silkrpc/core/remote_buffer_test.cpp
> +        RemoteState remoteBuffer(io_context, db_reader, block_number);
Same as above: probably `remote_state` or `state` could be better now than `remoteBuffer`

2022-03-31 17:38 UTC, enriavil1 commented
#242

2022-03-31 19:56 UTC, canepat approved these changes

2022-03-31 19:57 UTC, canepat commented
> #242

Thanks a lot @enriavil1 for bringing this PR to completion!

2022-03-31 19:57 UTC, merged