Perf auto1
torquem-ch/silkrpc pull request #29
Opened 2021-04-21 18:24 UTC by Paolob69

python script that manage automatic tests using command line parameters and report the results on csv file

2021-04-23 08:09 UTC, canepat requested changes

2021-04-23 08:09 UTC, canepat commented on tests/perf/perf.py
> +            thrds = os.popen("ps -efL | grep tg | wc -l").read().replace('\n', ' ')
`thrds` -> `threads`

2021-04-23 08:09 UTC, canepat commented on tests/perf/perf.py
> +        self.writer.writerow(["Daemon", "TestNo", "TG-Thrs", "Qps", "Time", "Min", "Mean", "50", "90", "95", "99", "Max"])
`"TG-Thrs"` -> `"TG-Threads"`

2021-04-23 08:09 UTC, canepat commented on tests/perf/perf.py
> +    def write_test_report(self, daemon, test_number, thrds, qps_value, time_value, min_latency, mean, fifty, ninty, nintyfive, nintynine, max_latency):
`thrds` -> `threads`

2021-04-23 08:09 UTC, canepat commented on tests/perf/perf.py
> +    config_class = Config(argv)
`config_class` -> `config`

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +DEFAULT_TEST_SEQUENCE = "50+30-200+30-200+60-400+30"
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +DEFAULT_REPETITION_VALUE = 10
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +DEFAULT_PATTERN_TAR_FILE = ""
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +        self.rep_tests = DEFAULT_REPETITION_VALUE
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +        self.pattern_tar_file = DEFAULT_PATTERN_TAR_FILE
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +    def __init__(self, test_report, config_class):
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +            thrds = os.popen("ps -efL | grep tg | wc -l").read().replace('\n', ' ')
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +        self.writer.writerow(["Daemon", "TestNo", "TG-Thrs", "Qps", "Time", "Min", "Mean", "50", "90", "95", "99", "Max"])
ok

2021-04-23 20:58 UTC, Paolob69 commented on tests/perf/perf.py
> +    def write_test_report(self, daemon, test_number, thrds, qps_value, time_value, min_latency, mean, fifty, ninty, nintyfive, nintynine, max_latency):
ok

2021-04-23 20:59 UTC, Paolob69 commented on tests/perf/perf.py
> +    config_class = Config(argv)
ok

2021-04-24 05:52 UTC, Paolob69 commented on tests/perf/perf.py
> +        elif len(argv) != 2:
ok

2021-04-24 08:26 UTC, canepat approved these changes

2021-04-24 08:48 UTC, merged