Added trace_filter API implementation
torquem-ch/silkrpc pull request #348
Opened 2022-09-20 09:17 UTC by Sixtysixter

trace_filter API implementation

2022-10-28 13:14 UTC, canepat requested changes
You should also update the `trace_filter` status in API doc

2022-10-28 13:14 UTC, canepat commented on silkrpc/core/evm_trace.hpp
> +    // boost::asio::awaitable<std::vector<Trace>> block_traces(const silkworm::BlockWithHash& block_with_hash);
Please remove commented code

2022-10-28 16:31 UTC, Sixtysixter commented on silkrpc/core/evm_trace.cpp
> +
Done

2022-10-28 16:32 UTC, Sixtysixter commented on silkrpc/core/evm_trace.cpp
> +
done

2022-10-29 15:05 UTC, canepat approved these changes

2022-10-29 15:05 UTC, merged