update Silkworm
torquem-ch/silkrpc pull request #436
Opened 2023-02-26 10:51 UTC by lupin012

2023-02-28 15:13 UTC, canepat requested changes

2023-02-28 15:13 UTC, canepat commented on silkworm/silkrpc/core/rawdb/chain.cpp
> +    silkworm::BlockWithHash block{silkworm::Block{body.transactions, body.ommers, std::nullopt, header}, block_hash};
This line of code could be written as:
```
silkworm::BlockWithHash block_with_hash{
    .block = {
        {
            .transactions = body.transactions,
            .ommers = body.ommers,
        },
        header
    },
    .hash = block_hash
};
```
to improve readability.

2023-02-28 15:13 UTC, canepat commented on silkworm/silkrpc/json/types_test.cpp
> +        std::nullopt,
Given that you're changing this declaration, it would be a good idea to use structure binding syntax to improve readability

2023-02-28 15:13 UTC, canepat commented on silkworm/silkrpc/json/types_test.cpp
> +            std::nullopt,
Same as before, structure binding syntax can improve readability here

2023-02-28 15:41 UTC, lupin012 commented on silkworm/silkrpc/commands/eth_api.cpp
> +                if (!decoding_result) {
yes

2023-02-28 17:17 UTC, lupin012 commented on silkworm/silkrpc/json/types_test.cpp
> +            std::nullopt,
ok

2023-03-02 07:10 UTC, canepat approved these changes

2023-03-02 07:10 UTC, merged