Eth get uncle by block hash and index
torquem-ch/silkrpc pull request #51
Opened 2021-05-04 16:05 UTC by Paolob69

implementation eth_getUncleCountByBlockHash, eth_getUncleByBlockHashAndIndex

2021-05-04 18:16 UTC, canepat commented on silkrpc/json/types.cpp
> +    json["mixHash"]= b.block.header.mix_hash;
:+1: Kudos for this fix!

2021-05-04 18:18 UTC, canepat requested changes

2021-05-04 18:18 UTC, canepat commented on docs/API.md
> +| eth_getUncleByBlockHashAndIndex         | Yes          | not yet implemented                        |
Remove `not yet implemented`

2021-05-04 18:18 UTC, canepat commented on docs/API.md
> +| eth_getUncleCountByBlockHash            | Yes          | not yet implemented                        |
Remove `not yet implemented`

2021-05-04 18:18 UTC, canepat commented on silkrpc/commands/eth_api.cpp
> +        auto error_msg = "invalid eth_getUncleByBlockHashIndex params: " + params.dump();
`eth_getUncleByBlockHashIndex` -> `eth_getUncleByBlockHashAndIndex`

2021-05-04 18:48 UTC, Paolob69 commented on docs/API.md
> +| eth_getUncleByBlockHashAndIndex         | Yes          | not yet implemented                        |
ok

2021-05-04 18:48 UTC, Paolob69 commented on docs/API.md
> +| eth_getUncleCountByBlockHash            | Yes          | not yet implemented                        |
ok

2021-05-04 18:51 UTC, Paolob69 commented on silkrpc/commands/eth_api.cpp
> +        auto error_msg = "invalid eth_getUncleByBlockHashIndex params: " + params.dump();
ok

2021-05-05 08:27 UTC, canepat approved these changes

2021-05-05 08:28 UTC, merged